name: DeathCube
version: 2.5
description: DeathCube v2.5
author: henningstorck
main: me.baba43.DeathCube.DeathCubeManager
softdepend: [ 'Multiverse-Core' ]

commands:
  dc:
    description: Deathcube Commands
    usage: /dc help
