name: DeathCube
version: 3.0.2
description: DeathCube v3.0.2
authors: [ baba43, henningrck ]
website: https://github.com/cubelegends/deathcube

main: me.baba43.deathcube.DeathCubeManager

softdepend: [ 'Multiverse-Core' ]
api-version: 1.13

commands:
  dc:
    description: Deathcube Commands
    usage: /dc help
